"""Merge per-recipe `mise.lock` files into the one lockfile a stack's tool install reads.

A stack's tool set is the UNION of its recipes' `tools:` (volumes.py / hostrun.py), composed at
launch. The pins are authored per RECIPE though, so the checksums are too: a recipe ships its own
`mise.lock` beside `recipe.yaml`, and assembly merges the ones its stack actually uses.

Four facts measured against mise 2026.8.3 before any of this was written, because each one would
have produced a mechanism that verifies nothing:

  1. mise ENFORCES the lockfile — a wrong checksum fails `mise install` with `Checksum mismatch`,
     exit 1. Without this the whole feature would be decorative.
  2. The file must be named `mise.lock`, NOT after the config. `$MISE_CONFIG_DIR/config.lock` and
     `config.toml.lock` are both silently IGNORED — install exits 0 on a corrupted checksum. That
     is the failure this module most needed to avoid, and only running it revealed the name.
  3. `mise lock` refuses to generate one for a global config ("No tools configured to lock"), so
     assembly cannot shell out to mise. The merge is ours to perform, which is why this file exists.
  4. Each tool's tables are CONTIGUOUS — `[[tools."<spec>"]]` followed by its `platforms.*` tables.
     That is what makes verbatim block extraction safe: unknown future fields are copied through
     untouched rather than lost to a re-serialisation this module would otherwise have to do.

Enforcement is per-tool, so adoption is incremental: a lockfile covering some of a stack's tools
verifies those and leaves the rest installing exactly as they do today.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path


class ToolLockError(Exception):
    """Two recipes in one stack disagree about a tool's locked bytes."""


# A tool's section starts at `[[tools."spec"]]` (the array-of-tables entry) or at one of its
# `[tools."spec"."platforms.x"]` tables. Both spellings carry the spec in the same position.
_SECTION_RE = re.compile(r'^\[\[?tools\."(?P<spec>[^"]+)"')


def _blocks(text: str) -> dict[str, str]:
    """Split a lockfile into verbatim per-tool text, keyed by spec.

    Verbatim on purpose. Parsing to objects and re-emitting would silently drop any field this
    module does not know about — and mise owns this format, not harnessed.
    """
    blocks: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines(keepends=True):
        match = _SECTION_RE.match(line)
        if match:
            # str(): a named group in a matched pattern is always present, but typeshed types
            # `group()` as `str | None` and the dict key must be a `str`.
            current = str(match.group("spec"))
            blocks.setdefault(current, [])
        if current is not None:
            blocks[current].append(line)
    return {spec: "".join(lines).rstrip("\n") + "\n" for spec, lines in blocks.items()}


def read_lock(path: Path) -> dict[str, str]:
    """Per-tool blocks from one recipe's lockfile, after proving the whole file parses.

    The parse is a validity gate, not the merge input: a lockfile that TOML cannot read would
    otherwise be concatenated into the stack's file and break every tool in it, not just its own.
    """
    text = path.read_text(encoding="utf-8")
    try:
        tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ToolLockError(f"{path}: not valid TOML — {exc}") from exc
    return _blocks(text)


def merge_locks(sources: dict[str, Path]) -> str:
    """Merge `{recipe name: lockfile path}` into one `mise.lock` body.

    Two recipes may legitimately pin the SAME tool — the stack's tool set is deduped, so `pulumi`
    appearing in two recipes is ordinary. Identical blocks therefore merge to one entry.

    Differing blocks for one spec FAIL CLOSED. That disagreement is exactly what a lockfile exists
    to surface: two recipes claiming different bytes for the same tool cannot both be satisfied, and
    picking a winner would mean one recipe silently installs something its own lockfile denies.
    """
    merged: dict[str, str] = {}
    owner: dict[str, str] = {}
    for recipe in sorted(sources):
        for spec, block in read_lock(sources[recipe]).items():
            if spec in merged and merged[spec] != block:
                raise ToolLockError(
                    f"recipes {owner[spec]!r} and {recipe!r} lock {spec!r} to different content. "
                    f"One tool cannot have two sets of bytes in one stack — align the two "
                    f"lockfiles, or split the recipes into different stacks."
                )
            merged.setdefault(spec, block)
            owner.setdefault(spec, recipe)
    if not merged:
        return ""
    header = (
        "# @generated by harnessed — merged from the lockfiles of this stack's recipes.\n"
        "# Edit a recipe's own mise.lock, never this file.\n"
    )
    return header + "\n" + "\n".join(merged[spec] for spec in sorted(merged))


def recipe_lock_path(recipe_root: Path) -> Path | None:
    """A recipe's own lockfile, or None when it ships none.

    Absent is NOT an error: no recipe has one today, so requiring it would break every stack at
    once. Absent means "these tools install unverified, as they do now" — the same posture the
    catalog has always had, kept until a recipe opts in.
    """
    candidate = recipe_root / "mise.lock"
    return candidate if candidate.is_file() else None
